#!/bin/bash

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cd "$ROOT_DIR" || exit 1
./node_modules/.bin/wdio wdio.conf.js "$@"

if [ $? -ne 0 ]; then
  tput setaf 1 && tput bold
  echo "Tests failed!"
  tput sgr0
fi

exit 0
